### ISSUE TITLE
NPE JsHint#toError

### ISSUE THREAD

**Issue by uwolfer** [gildur/jshint4j#2]
Got this while trying to use it together with sputnik:

```
Exception in thread "main" java.lang.NullPointerException
        at pl.gildur.jshint4j.JsHint.toError(JsHint.java:56)
        at pl.gildur.jshint4j.JsHint.lint(JsHint.java:49)
        at pl.gildur.jshint4j.JsHint.lint(JsHint.java:35)
        at pl.touk.sputnik.processor.jshint.JsHintProcessor.lintFile(JsHintProcessor.java:50)
        at pl.touk.sputnik.processor.jshint.JsHintProcessor.processFile(JsHintProcessor.java:42)
        at pl.touk.sputnik.processor.jshint.JsHintProcessor.process(JsHintProcessor.java:36)
        at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:24)
        at pl.touk.sputnik.engine.Engine.run(Engine.java:33)
        at pl.touk.sputnik.Main.main(Main.java:37)
```

If you need any additional information, please let me know.

**Comment by uwolfer** [comment]
Tested. Works fine now. Thank you.

**Comment by gildur** [comment]
Thanks for the info.
